version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 40
    ignore:
      - dependency-name: "@angular/*"
        versions:
          - ">=0"
      - dependency-name: "@angular-builders/*"
        versions:
          - ">=0"
      - dependency-name: "@angular-devkit/build-angular"
        versions:
          - ">=0"
      - dependency-name: "@mdi/angular-material"
        versions:
          - ">=5"
      - dependency-name: ng-packagr
        versions:
          - ">=13"
      - dependency-name: typescript
        versions:
          - ">=0"
      - dependency-name: "@types/node"
        versions:
          - ">=13"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: npm
    directory: "/showcase"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@angular/*"
        versions:
          - ">=0"
      - dependency-name: typescript
        versions:
          - ">=0"
      - dependency-name: "@types/node"
        versions:
          - ">=13"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: npm
    directory: "/starter"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@angular/*"
        versions:
          - ">=0"
      - dependency-name: typescript
        versions:
          - ">=0"
      - dependency-name: "@types/node"
        versions:
          - ">=13"
    commit-message:
      prefix: chore
      include: scope
