apiVersion: v1
kind: Service
metadata:
  name: stark-start
spec:
  selector:
    app: stark-start
    tier: backend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stark-start
spec:
  selector:
    matchLabels:
      app: stark-start
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: stark-start
        tier: backend
        track: stable
    spec:
      containers:
        - name: stark-start
          image: 'bourrierf/stark-start'
          ports:
            - name: http
              containerPort: 3000
