apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: stark-prod
spec:
  selector:
    matchLabels:
      app: stark-prod
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: stark-prod
        tier: backend
        track: stable
    spec:
      containers:
        - name: stark-prod
          image: 'registre.domaine.lan:5000/stark-prod'
          resources:
            requests:
                cpu: 300m
          ports:
            - name: http
              containerPort: 8080
