FROM node:latest AS build-stage

MAINTAINER NationalBankBelgium - BOURRIER Francois

WORKDIR /usr/projet/

RUN apt-get update -y -q && apt-get install git-sh rsync -y && apt-get upgrade -y -q

RUN git clone https://github.com/NationalBankBelgium/stark.git .

RUN npm install

RUN npm run install:all

RUN cd starter && npm run build:dev:monitor

#################
#	 STAGE 2	#
#################

FROM tomcat:latest AS server-stage

COPY --from=build-stage /usr/projet/starter/dist /usr/local/tomcat/webapps/ROOT

ADD server.xml /usr/local/tomcat/conf/
ADD rewrite.config /usr/local/tomcat/conf/Catalina/localhost/

ENV HOST=0.0.0.0

